import { defineConfig } from 'vitepress'

export default defineConfig({
  title: 'GCF',
  description: 'Token-optimized wire format for LLM tool responses',
  appearance: 'force-dark',
  base: '/',
  head: [
    ['link', { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
    ['link', { rel: 'icon', type: 'image/png', sizes: '32x32', href: '/favicon-32x32.png' }],
    ['link', { rel: 'icon', type: 'image/png', sizes: '16x16', href: '/favicon-16x16.png' }],
    ['link', { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' }],
    ['link', { rel: 'manifest', href: '/site.webmanifest' }],
    ['meta', { property: 'og:title', content: 'GCF' }],
    ['meta', { property: 'og:description', content: 'AI-native wire format for structured data. 71% fewer input tokens. 63% fewer output tokens. 100% comprehension accuracy on every frontier model. 2,500+ evaluations. Zero training.' }],
    ['meta', { property: 'og:type', content: 'website' }],
    ['meta', { property: 'og:url', content: 'https://gcformat.com/' }],
    ['meta', { property: 'og:image', content: 'https://gcformat.com/og.png' }],
    ['meta', { name: 'twitter:card', content: 'summary' }],
    ['meta', { name: 'twitter:title', content: 'GCF' }],
    ['meta', { name: 'twitter:description', content: 'AI-native wire format for structured data. 71% fewer input tokens. 63% fewer output tokens. 100% comprehension on every frontier model. 2,500+ evaluations. Zero training.' }],
    ['meta', { name: 'keywords', content: 'GCF, LLM, tokens, wire format, MCP, TOON, JSON alternative, token efficiency, agent communication, AI pipelines' }],
    ['link', { rel: 'canonical', href: 'https://gcformat.com/' }],
  ],
  themeConfig: {
    nav: [
      { text: 'Playground', link: '/playground' },
      { text: 'Cost Calculator', link: '/calculator' },
      { text: 'Guide', link: '/guide/getting-started' },
      { text: 'GCF vs TOON', link: '/guide/vs-toon' },
      { text: 'Benchmarks', link: '/guide/benchmarks' },
      { text: 'Whitepaper', link: '/whitepaper' },
      { text: 'Reference', link: '/reference/spec' },
    ],
    sidebar: [
      {
        text: 'Guide',
        items: [
          { text: 'Getting Started', link: '/guide/getting-started' },
          { text: 'Format Overview', link: '/guide/format-overview' },
          { text: 'Using GCF with LLMs', link: '/guide/llm-integration' },
          { text: 'MCP Integration', link: '/guide/mcp' },
          { text: 'MCP Proxy (Zero-Code)', link: '/guide/proxy' },
          { text: 'Claude Code Plugin', link: '/guide/claude-code' },
          { text: 'Codex Plugin', link: '/guide/codex' },
          { text: 'Schema Validation', link: '/guide/schema-validation' },
          { text: 'FAQ', link: '/guide/faq' },
        ],
      },
      {
        text: 'Advanced',
        items: [
          { text: 'Streaming Encoding', link: '/guide/streaming' },
          { text: 'Session Deduplication', link: '/guide/sessions' },
          { text: 'Delta Encoding', link: '/guide/delta' },
        ],
      },
      {
        text: 'Evidence',
        items: [
          { text: 'Testing and Verification', link: '/guide/testing' },
          { text: 'Benchmarks', link: '/guide/benchmarks' },
          { text: 'Tokenizer Analysis', link: '/guide/tokenizer-analysis' },
          { text: 'BPE and Attention', link: '/guide/bpe-and-attention' },
          { text: 'GCF vs TOON', link: '/guide/vs-toon' },
          { text: 'Benchmarks (Full Data)', link: '/guide/eval-results' },
          { text: 'Lossless Verification', link: '/guide/lossless-verification' },
          { text: 'Whitepaper', link: '/whitepaper' },
          { text: 'Independent AI Reviews', link: '/reviews/' },
        ],
      },
      {
        text: 'Reference',
        items: [
          { text: 'Specification', link: '/reference/spec' },
          { text: 'Syntax Cheatsheet', link: '/reference/cheatsheet' },
          { text: 'Token Savings Proof', link: '/reference/token-savings-proof' },
          { text: 'API (Go)', link: '/reference/api-go' },
          { text: 'API (TypeScript)', link: '/reference/api-typescript' },
          { text: 'API (Python)', link: '/reference/api-python' },
          { text: 'API (Rust)', link: '/reference/api-rust' },
          { text: 'API (Swift)', link: '/reference/api-swift' },
          { text: 'API (Kotlin)', link: '/reference/api-kotlin' },
        ],
      },
      {
        text: 'Ecosystem',
        items: [
          { text: 'Implementations', link: '/ecosystem/implementations' },
          { text: 'Who Uses GCF', link: '/ecosystem/adopters' },
          { text: 'Case Study: NeuroNest', link: '/ecosystem/case-study-neuronest' },
        ],
      },
    ],
    logo: '/gcf-logo.png',
    siteTitle: false,
    socialLinks: [
      { icon: 'github', link: 'https://github.com/blackwell-systems/gcf' },
      { icon: 'linkedin', link: 'https://www.linkedin.com/in/daynablackwell/' },
    ],
    footer: {
      message: '100% comprehension. 71% fewer tokens. 2,400+ LLM evaluations.',
      copyright: '&copy; 2026 <a href="https://blackwell-systems.com">Blackwell Systems</a>. MIT Licensed.',
    },
  },
})
